[package]
name = "fg_engine"
version = "0.1.0"
authors = ["Angel of Sol <julietckilian@gmail.com>"]
edition = "2018"

[dependencies]
ggez = "0.5.1"
winit = "0.19.3"
nalgebra = { version = "0.18.1", features = ["serde-serialize", "mint"] }
mint = "0.5.3"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"
gfx_core = "0.9.2"
gfx_device_gl = "0.16.2"
imgui = "0.2.1"
imgui-gfx-renderer = "0.2.0"
imgui-sys = "0.2.0"
nfd = "0.0.4"
rgb = "0.8.14"
tar = "0.4.26"
image = "0.22.3"
gfx = "0.18.2"
gilrs = "0.7.2"
