[package]
name = "fg_engine"
version = "0.1.0"
authors = ["Angel of Sol <julietckilian@gmail.com>"]
edition = "2018"

[dependencies]
ggez = "^0.5.0-rc.2"
nalgebra = { version = "0.18", features = ["serde-serialize", "mint"] }
mint = "0.5"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
