[package]
name = "fg_engine"
version = "0.1.0"
authors = ["Angel of Sol <julietckilian@gmail.com>"]
edition = "2018"

[dependencies]
ggez = "^0.5.0-rc.2"
nalgebra = { version = "0.18", features = ["serde-serialize", "mint"] }
mint = "0.5"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
gfx_core = "0.9.1"
gfx_device_gl = "0.16.1"
imgui = "0.0.23"
imgui-gfx-renderer = "0.0.23"
imgui-sys = "0.0.23"
nfd = "0.0.4"
rgb = "0.8.13"
tar = "0.4.26"
image = "0.21.2"
